@startuml
actor "Client" as client
participant "API Gateway/Lambda" as apiGateway
participant "GetOrderActivity" as getOrderActivity
participant "OrderDao" as OrderDao
database "DynamoDB" as dynamoDB

title Get Order Activity

client -> apiGateway : HTTP Request

activate apiGateway
apiGateway -> getOrderActivity : getOrderRequest(orderId)

activate getOrderActivity
getOrderActivity -> OrderDao : getOrder(orderId)

activate OrderDao
OrderDao -> dynamoDB : Get Order (orderId)

activate dynamoDB
alt if (orderId) is invalid
dynamoDB --> OrderDao : invalid (orderId)
OrderDao --> getOrderActivity : invalid (orderId)
getOrderActivity --> apiGateway : invalid (orderId)
apiGateway --> client : invalid (orderId)
else else continue
end

dynamoDB --> OrderDao : Order
deactivate dynamoDB

OrderDao --> getOrderActivity : Order
deactivate OrderDao

getOrderActivity --> apiGateway : Order
deactivate getOrderActivity

apiGateway --> client : Order
deactivate apiGateway
@enduml
