@startuml
actor "Client" as client
participant "API Gateway/Lambda" as apiGateway
participant "PlaceOrderActivity" as placeOrderActivity
participant "OrderDao" as OrderDao
database "DynamoDB" as dynamoDB

title Place Order Activity
client -> apiGateway : HTTP Request

activate apiGateway
apiGateway -> placeOrderActivity : placeOrderRequest(Order)

activate placeOrderActivity
alt if Order is invalid
placeOrderActivity --> apiGateway : ThrowInvalidOrderException
apiGateway --> client : Response Code 300
else else continue
end
placeOrderActivity -> OrderDao : saveOrder(Order)

activate OrderDao
OrderDao -> dynamoDB : save(Order)

activate dynamoDB
dynamoDB --> OrderDao : Order data
deactivate dynamoDB

OrderDao --> placeOrderActivity : Order
deactivate OrderDao

placeOrderActivity --> apiGateway : PlaceOrderResponse
deactivate placeOrderActivity

apiGateway --> client : Order Confirmation
deactivate apiGateway
@enduml
