@startuml
actor "Client" as client
participant "API Gateway/Lambda" as apiGateway
participant "UpdateMenuItemActivity" as updateMenuItemActivity
participant "OrderDao" as OrderDao
database "DynamoDB" as dynamoDB

title Update MenuItem in Cart
client -> apiGateway : HTTP Request

activate apiGateway
apiGateway -> updateMenuItemActivity : AddItemRequest

activate updateMenuItemActivity
updateMenuItemActivity -> OrderDao : AddItemRequest

activate OrderDao
OrderDao -> dynamoDB : add MenuItem

activate dynamoDB
dynamoDB -> OrderDao : Order
deactivate dynamoDB

OrderDao -> updateMenuItemActivity : Order
deactivate OrderDao

updateMenuItemActivity -> apiGateway : Order
deactivate updateMenuItemActivity

apiGateway -> client : Order
deactivate apiGateway
@enduml
